language: c

env:
  - PLATFORM=K64F
  - PLATFORM=DISCO_F429ZI
  - PLATFORM=EFM32GG_STK3700

python:
- "2.7"

sudo: required

script:
# Tells mbed-cli that the current directory is a project even though you didnt do an `mbed import` (helps suppress some warning messages)
- mbed config root .
# Pull in mbed-os and other dependencies
- mbed deploy
- sudo pip install -r mbed-os/requirements.txt
- mbed compile --clean -m $PLATFORM -t GCC_ARM
- mbed compile --clean -m $PLATFORM -t GCC_ARM --profile debug

before_install:
- sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq gcc-arm-embedded --force-yes
# Print versions we use
- arm-none-eabi-gcc --version
- python --version

install:
- sudo pip install mbed-cli
- sudo pip install pytest
- sudo pip install pylint
- sudo pip install hypothesis
- sudo pip install mock
